language: python
python:
    - '3.5.2'

install:
    - pip install -r requirement.txt
    - pip install pytest pytest-cov codecov

script: pytest --cov=./

sudo: enabled

after_success:
    - codecov
